/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package ca.mimic.apphangar;

public final class R {
    public static final class anim {
        public static final int refresh=0x7f040000;
    }
    public static final class array {
        public static final int entries_action_spinner=0x7f060000;
        public static final int entries_alignment_preference=0x7f060001;
        public static final int entries_apps_widget_appsno_preference=0x7f060002;
        public static final int entries_appsno_preference=0x7f060003;
        public static final int entries_google_donate=0x7f060004;
        public static final int entries_icon_size_preference=0x7f060005;
        public static final int entries_notification_bg_preference=0x7f060006;
        public static final int entries_pinned_placement_preference=0x7f060007;
        public static final int entries_pinned_sort_preference=0x7f060008;
        public static final int entries_priority_preference=0x7f060009;
        public static final int entries_sort_spinner=0x7f06000a;
        public static final int entries_stats_widget_appsno_ls_preference=0x7f06000b;
        public static final int entries_stats_widget_appsno_preference=0x7f06000c;
        public static final int entries_statusbar_icon_preference=0x7f06000d;
        public static final int entries_top_spinner=0x7f06000e;
        public static final int entries_weight_priority_preference=0x7f06000f;
        public static final int values_alignment_preference=0x7f060010;
        public static final int values_icon_size_preference=0x7f060011;
        public static final int values_more_apps_pages_preference=0x7f060012;
        public static final int values_notification_bg_preference=0x7f060013;
        public static final int values_pinned_placement_preference=0x7f060014;
        public static final int values_pinned_sort_preference=0x7f060015;
        public static final int values_priority_preference=0x7f060016;
        public static final int values_statusbar_icon_preference=0x7f060017;
        public static final int values_weight_priority_preference=0x7f060018;
        public static final int versionNumbers=0x7f060019;
        public static final int versionSummaries=0x7f06001a;
    }
    public static final class attr {
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int centered=0x7f010000;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int clipPadding=0x7f01000b;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fadeDelay=0x7f010017;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fadeLength=0x7f010018;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fades=0x7f010016;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fillColor=0x7f010004;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int footerColor=0x7f01000c;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int footerIndicatorHeight=0x7f01000f;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>triangle</code></td><td>1</td><td></td></tr>
<tr><td><code>underline</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int footerIndicatorStyle=0x7f01000e;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int footerIndicatorUnderlinePadding=0x7f010010;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int footerLineHeight=0x7f01000d;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int footerPadding=0x7f010011;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int gapWidth=0x7f01000a;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>bottom</code></td><td>0</td><td></td></tr>
<tr><td><code>top</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int linePosition=0x7f010012;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int lineWidth=0x7f010009;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pageColor=0x7f010005;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int radius=0x7f010006;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int selectedBold=0x7f010013;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int selectedColor=0x7f010001;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int snap=0x7f010007;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int strokeColor=0x7f010008;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int strokeWidth=0x7f010002;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int titlePadding=0x7f010014;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int topPadding=0x7f010015;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int unselectedColor=0x7f010003;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int vpiCirclePageIndicatorStyle=0x7f010019;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int vpiIconPageIndicatorStyle=0x7f01001a;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int vpiLinePageIndicatorStyle=0x7f01001b;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int vpiTabPageIndicatorStyle=0x7f01001d;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int vpiTitlePageIndicatorStyle=0x7f01001c;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int vpiUnderlinePageIndicatorStyle=0x7f01001e;
    }
    public static final class bool {
        public static final int default_circle_indicator_centered=0x7f070000;
        public static final int default_circle_indicator_snap=0x7f070001;
        public static final int notification_needs_scaling=0x7f070003;
        public static final int wrap_dialog_buttons=0x7f070002;
    }
    public static final class color {
        public static final int applist_action_line_color=0x7f080000;
        public static final int default_circle_indicator_fill_color=0x7f080001;
        public static final int default_circle_indicator_page_color=0x7f080002;
        public static final int default_circle_indicator_stroke_color=0x7f080003;
    }
    public static final class dimen {
        public static final int default_circle_indicator_radius=0x7f090000;
        public static final int default_circle_indicator_stroke_width=0x7f090001;
    }
    public static final class drawable {
        public static final int crowdin=0x7f020000;
        public static final int empty_bg=0x7f020001;
        public static final int github_icon=0x7f020002;
        public static final int google_play=0x7f020003;
        public static final int google_plus=0x7f020004;
        public static final int ic_action_apps_widget=0x7f020005;
        public static final int ic_action_refresh=0x7f020006;
        public static final int ic_action_settings=0x7f020007;
        public static final int ic_action_stats_widget=0x7f020008;
        public static final int ic_alert=0x7f020009;
        public static final int ic_apps_blue=0x7f02000a;
        public static final int ic_apps_blue_black=0x7f02000b;
        public static final int ic_apps_cold=0x7f02000c;
        public static final int ic_apps_cold_black=0x7f02000d;
        public static final int ic_apps_plus=0x7f02000e;
        public static final int ic_apps_transparent=0x7f02000f;
        public static final int ic_apps_warm=0x7f020010;
        public static final int ic_apps_warm_black=0x7f020011;
        public static final int ic_apps_white=0x7f020012;
        public static final int ic_apps_widget_preview=0x7f020013;
        public static final int ic_cab_done_holo_dark=0x7f020014;
        public static final int ic_launcher=0x7f020015;
        public static final int ic_launcher_home=0x7f020016;
        public static final int ic_logo=0x7f020017;
        public static final int ic_stats_widget_preview=0x7f020018;
        public static final int instructions_1=0x7f020019;
        public static final int instructions_2=0x7f02001a;
        public static final int instructions_3=0x7f02001b;
        public static final int instructions_4=0x7f02001c;
        public static final int pin_icon=0x7f02001d;
        public static final int rounded_bg=0x7f02001e;
        public static final int rounded_bg_bottom=0x7f02001f;
        public static final int rounded_bg_top=0x7f020020;
    }
    public static final class id {
        public static final int action_blacklist=0x7f0e0042;
        public static final int action_changelog=0x7f0e0045;
        public static final int action_contribute=0x7f0e0044;
        public static final int action_donate=0x7f0e0047;
        public static final int action_instructions=0x7f0e0046;
        public static final int action_license=0x7f0e0048;
        public static final int action_pick_icon=0x7f0e0041;
        public static final int action_pin=0x7f0e0040;
        public static final int action_reset_stats=0x7f0e0043;
        public static final int appCont=0x7f0e0037;
        public static final int appName=0x7f0e0039;
        public static final int applist_action_bar=0x7f0e000c;
        public static final int applist_action_bar_scroll=0x7f0e000b;
        public static final int applist_action_line=0x7f0e0013;
        public static final int appsWidget=0x7f0e001d;
        public static final int barImg=0x7f0e003a;
        public static final int bar_cont=0x7f0e0016;
        public static final int bottom=0x7f0e0003;
        public static final int button4=0x7f0e0032;
        public static final int changeParent=0x7f0e0020;
        public static final int check=0x7f0e002f;
        public static final int clickCont=0x7f0e0038;
        public static final int color_picker_view=0x7f0e0025;
        public static final int config_spinner=0x7f0e0005;
        public static final int contribute_code=0x7f0e0023;
        public static final int contribute_google=0x7f0e0021;
        public static final int contribute_plus=0x7f0e0024;
        public static final int contribute_translate=0x7f0e0022;
        public static final int corners=0x7f0e003f;
        public static final int donate_contribute=0x7f0e002a;
        public static final int donate_google=0x7f0e002b;
        public static final int donate_spinner=0x7f0e002c;
        public static final int hex_val=0x7f0e0027;
        public static final int icon=0x7f0e002d;
        public static final int iconCont=0x7f0e003c;
        public static final int iconpack_warning=0x7f0e0030;
        public static final int imageButton=0x7f0e001c;
        public static final int imageCont=0x7f0e001b;
        public static final int indicator=0x7f0e0031;
        public static final int license_view_source=0x7f0e0033;
        public static final int list=0x7f0e000a;
        public static final int loading_text=0x7f0e0009;
        public static final int new_color_panel=0x7f0e0029;
        public static final int none=0x7f0e0000;
        public static final int notifContainer=0x7f0e0034;
        public static final int notifRow=0x7f0e0035;
        public static final int old_color_panel=0x7f0e0028;
        public static final int pager=0x7f0e0008;
        public static final int pin_icon=0x7f0e0019;
        public static final int placementButton=0x7f0e003d;
        public static final int refresh=0x7f0e0012;
        public static final int rootBackground=0x7f0e001e;
        public static final int row_cont=0x7f0e0014;
        public static final int separator=0x7f0e000f;
        public static final int shape=0x7f0e003e;
        public static final int sort_spinner=0x7f0e000e;
        public static final int sort_text=0x7f0e000d;
        public static final int spinner_icon=0x7f0e0006;
        public static final int spinner_text=0x7f0e0007;
        public static final int statsCont=0x7f0e003b;
        public static final int taskRoot=0x7f0e0036;
        public static final int task_icon=0x7f0e0018;
        public static final int task_name=0x7f0e0015;
        public static final int text_hex_wrapper=0x7f0e0026;
        public static final int title=0x7f0e002e;
        public static final int top=0x7f0e0004;
        public static final int top_spinner=0x7f0e0011;
        public static final int top_text=0x7f0e0010;
        public static final int triangle=0x7f0e0001;
        public static final int underline=0x7f0e0002;
        public static final int use_stats=0x7f0e0017;
        public static final int viewCont=0x7f0e001a;
        public static final int viewRow=0x7f0e001f;
    }
    public static final class integer {
        public static final int default_circle_indicator_orientation=0x7f0a0000;
        public static final int notification_icon_size=0x7f0a0001;
        public static final int notification_row_value=0x7f0a0002;
    }
    public static final class layout {
        public static final int action_spinner=0x7f030000;
        public static final int action_spinner_item=0x7f030001;
        public static final int activity_settings=0x7f030002;
        public static final int appearance_settings=0x7f030003;
        public static final int apps_settings=0x7f030004;
        public static final int apps_settings_row=0x7f030005;
        public static final int apps_widget=0x7f030006;
        public static final int apps_widget_item=0x7f030007;
        public static final int apps_widget_row=0x7f030008;
        public static final int apps_widget_row_large=0x7f030009;
        public static final int apps_widget_row_small=0x7f03000a;
        public static final int apps_widget_settings=0x7f03000b;
        public static final int behavior_settings=0x7f03000c;
        public static final int changelog=0x7f03000d;
        public static final int contribute=0x7f03000e;
        public static final int dialog_color_picker=0x7f03000f;
        public static final int donate=0x7f030010;
        public static final int general_settings=0x7f030011;
        public static final int iconpack_chooser=0x7f030012;
        public static final int iconpack_main=0x7f030013;
        public static final int instructions=0x7f030014;
        public static final int instructions_img_1=0x7f030015;
        public static final int instructions_img_2=0x7f030016;
        public static final int instructions_img_3=0x7f030017;
        public static final int instructions_img_4=0x7f030018;
        public static final int instructions_page_1=0x7f030019;
        public static final int instructions_page_2=0x7f03001a;
        public static final int instructions_page_3=0x7f03001b;
        public static final int instructions_page_4=0x7f03001c;
        public static final int license=0x7f03001d;
        public static final int notification=0x7f03001e;
        public static final int notification_item=0x7f03001f;
        public static final int notification_item_large=0x7f030020;
        public static final int notification_item_small=0x7f030021;
        public static final int notification_no_dividers=0x7f030022;
        public static final int notification_row=0x7f030023;
        public static final int notification_row_no_dividers=0x7f030024;
        public static final int spinner_item=0x7f030025;
        public static final int stats_widget=0x7f030026;
        public static final int stats_widget_no_dividers=0x7f030027;
        public static final int stats_widget_row=0x7f030028;
        public static final int stats_widget_settings=0x7f030029;
        public static final int us_permission=0x7f03002a;
        public static final int widget_footer=0x7f03002b;
    }
    public static final class menu {
        public static final int app_action=0x7f0d0000;
        public static final int settings=0x7f0d0001;
    }
    public static final class string {
        public static final int action_blacklist=0x7f0b0000;
        public static final int action_pick_icon=0x7f0b0001;
        public static final int action_pin=0x7f0b0002;
        public static final int action_reset_stats=0x7f0b0003;
        public static final int action_unpin=0x7f0b0004;
        public static final int aesthetics_category=0x7f0b0005;
        public static final int alert_floating_windows=0x7f0b0006;
        public static final int alert_message_statusbar_icon_preference=0x7f0b0007;
        public static final int alert_second_row_summary=0x7f0b0008;
        public static final int alert_title_statusbar_icon_preference=0x7f0b0009;
        public static final int alignment_bottom=0x7f0b000a;
        public static final int alignment_center=0x7f0b000b;
        public static final int alignment_top=0x7f0b000c;
        public static final int app_name=0x7f0b000d;
        public static final int apps_loading=0x7f0b000e;
        public static final int apps_widget_name=0x7f0b000f;
        public static final int appsno_category=0x7f0b0010;
        public static final int arrow_down=0x7f0b0011;
        public static final int arrow_right=0x7f0b0012;
        public static final int automatic_appsno=0x7f0b0013;
        public static final int button_name=0x7f0b0014;
        public static final int changelog_accept_button=0x7f0b0015;
        public static final int changelog_changes_title=0x7f0b0016;
        public static final int changelog_coming_soon_text=0x7f0b0017;
        public static final int changelog_coming_soon_title=0x7f0b0018;
        public static final int changelog_contribute_button=0x7f0b0019;
        public static final int changelog_donate_button=0x7f0b001a;
        public static final int changelog_title=0x7f0b001b;
        public static final int configure_changelog=0x7f0b001c;
        public static final int configure_contribute=0x7f0b001d;
        public static final int configure_donate=0x7f0b001e;
        public static final int configure_instructions=0x7f0b001f;
        public static final int configure_license=0x7f0b0020;
        public static final int contribute_accept_button=0x7f0b0021;
        public static final int contribute_code_link=0x7f0b0022;
        public static final int contribute_code_text=0x7f0b0023;
        public static final int contribute_code_title=0x7f0b0024;
        public static final int contribute_code_url=0x7f0b0025;
        public static final int contribute_google_link=0x7f0b0026;
        public static final int contribute_google_text=0x7f0b0027;
        public static final int contribute_google_title=0x7f0b0028;
        public static final int contribute_google_url=0x7f0b0029;
        public static final int contribute_plus_link=0x7f0b002a;
        public static final int contribute_plus_text=0x7f0b002b;
        public static final int contribute_plus_title=0x7f0b002c;
        public static final int contribute_plus_url=0x7f0b002d;
        public static final int contribute_title=0x7f0b002e;
        public static final int contribute_translate_link=0x7f0b002f;
        public static final int contribute_translate_text=0x7f0b0030;
        public static final int contribute_translate_title=0x7f0b0031;
        public static final int contribute_translate_url=0x7f0b0032;
        public static final int contributors_name1=0x7f0b0033;
        public static final int contributors_name10=0x7f0b0034;
        public static final int contributors_name11=0x7f0b0035;
        public static final int contributors_name2=0x7f0b0036;
        public static final int contributors_name3=0x7f0b0037;
        public static final int contributors_name4=0x7f0b0038;
        public static final int contributors_name5=0x7f0b0039;
        public static final int contributors_name6=0x7f0b003a;
        public static final int contributors_name7=0x7f0b003b;
        public static final int contributors_name8=0x7f0b003c;
        public static final int contributors_name9=0x7f0b003d;
        public static final int contributors_role1=0x7f0b003e;
        public static final int contributors_role10=0x7f0b003f;
        public static final int contributors_role11=0x7f0b0040;
        public static final int contributors_role2=0x7f0b0041;
        public static final int contributors_role3=0x7f0b0042;
        public static final int contributors_role4=0x7f0b0043;
        public static final int contributors_role5=0x7f0b0044;
        public static final int contributors_role6=0x7f0b0045;
        public static final int contributors_role7=0x7f0b0046;
        public static final int contributors_role8=0x7f0b0047;
        public static final int contributors_role9=0x7f0b0048;
        public static final int contributors_special_thanks=0x7f0b0049;
        public static final int contributors_title=0x7f0b004a;
        public static final int default_icon_pack=0x7f0b004b;
        public static final int dialog_appsno_preference=0x7f0b004c;
        public static final int dialog_color_picker=0x7f0b004d;
        public static final int dialog_priority_preference=0x7f0b004e;
        public static final int dialog_statusbar_icon_preference=0x7f0b004f;
        public static final int dialog_weight_priority_preference=0x7f0b0050;
        public static final int donate_accept_button=0x7f0b0051;
        public static final int donate_contribute=0x7f0b0052;
        public static final int donate_google=0x7f0b0053;
        public static final int donate_head=0x7f0b0054;
        public static final int donate_sorry=0x7f0b0055;
        public static final int donate_thanks=0x7f0b0056;
        public static final int donate_thanks_continue=0x7f0b0057;
        public static final int donate_thanks_title=0x7f0b0058;
        public static final int donate_title=0x7f0b0059;
        public static final int donate_title_google=0x7f0b005a;
        public static final int hex=0x7f0b005b;
        public static final int icon_size_large=0x7f0b005c;
        public static final int icon_size_medium=0x7f0b005d;
        public static final int icon_size_small=0x7f0b005e;
        public static final int instructions_1_1=0x7f0b005f;
        public static final int instructions_1_2=0x7f0b0060;
        public static final int instructions_1_3=0x7f0b0061;
        public static final int instructions_1_swipe=0x7f0b0062;
        public static final int instructions_2_1=0x7f0b0063;
        public static final int instructions_2_2=0x7f0b0064;
        public static final int instructions_2_3=0x7f0b0065;
        public static final int instructions_3_1=0x7f0b0066;
        public static final int instructions_3_2=0x7f0b0067;
        public static final int instructions_3_3=0x7f0b0068;
        public static final int instructions_4_1=0x7f0b0069;
        public static final int instructions_4_2=0x7f0b006a;
        public static final int instructions_4_button=0x7f0b006b;
        public static final int instructions_title=0x7f0b006c;
        public static final int instructions_title_1=0x7f0b006d;
        public static final int instructions_title_2=0x7f0b006e;
        public static final int instructions_title_3=0x7f0b006f;
        public static final int instructions_title_4=0x7f0b0070;
        public static final int license_accept_button=0x7f0b0071;
        public static final int license_github_url=0x7f0b0072;
        public static final int license_head=0x7f0b0073;
        public static final int license_title=0x7f0b0074;
        public static final int license_view_source=0x7f0b0075;
        public static final int notification_bg_black=0x7f0b0076;
        public static final int notification_bg_dark=0x7f0b0077;
        public static final int notification_bg_default=0x7f0b0078;
        public static final int pinned_placement_left=0x7f0b0079;
        public static final int pinned_placement_right=0x7f0b007a;
        public static final int pinned_sort_added=0x7f0b007b;
        public static final int pinned_sort_alphabetical=0x7f0b007c;
        public static final int pinned_sort_last_opened=0x7f0b007d;
        public static final int pinned_sort_time=0x7f0b007e;
        public static final int press_color_to_apply=0x7f0b007f;
        public static final int priority_bottom=0x7f0b0080;
        public static final int priority_normal=0x7f0b0081;
        public static final int priority_on_l_accept_button=0x7f0b0082;
        public static final int priority_on_l_cancel_button=0x7f0b0083;
        public static final int priority_top=0x7f0b0084;
        public static final int reconfigure_button_name=0x7f0b0085;
        public static final int reconfigure_reminder=0x7f0b0086;
        public static final int refresh_button=0x7f0b0087;
        public static final int reset_icon=0x7f0b0088;
        public static final int sort_alphabetical=0x7f0b0089;
        public static final int sort_time_spent=0x7f0b008a;
        public static final int stats_widget_name=0x7f0b008b;
        public static final int statusbar_icon_all_white=0x7f0b008c;
        public static final int statusbar_icon_blue_black=0x7f0b008d;
        public static final int statusbar_icon_blue_white=0x7f0b008e;
        public static final int statusbar_icon_cold_black=0x7f0b008f;
        public static final int statusbar_icon_cold_white=0x7f0b0090;
        public static final int statusbar_icon_none=0x7f0b0091;
        public static final int statusbar_icon_transparent=0x7f0b0092;
        public static final int statusbar_icon_warm_black=0x7f0b0093;
        public static final int statusbar_icon_warm_white=0x7f0b0094;
        public static final int summary_apps_by_widget_size_preference=0x7f0b0095;
        public static final int summary_appsno_preference=0x7f0b0096;
        public static final int summary_appsno_second_row_preference=0x7f0b0097;
        public static final int summary_colorize_preference=0x7f0b0098;
        public static final int summary_divider_preference=0x7f0b0099;
        public static final int summary_floating_windows=0x7f0b009a;
        public static final int summary_more_apps=0x7f0b009b;
        public static final int summary_more_apps_pages=0x7f0b009c;
        public static final int summary_notification_bg_preference=0x7f0b009d;
        public static final int summary_priority_on_l_notification=0x7f0b009e;
        public static final int summary_priority_preference=0x7f0b009f;
        public static final int summary_row_divider_preference=0x7f0b00a0;
        public static final int summary_second_row_preference=0x7f0b00a1;
        public static final int summary_smart_notification=0x7f0b00a2;
        public static final int summary_stats_widget_appsno_ls_preference=0x7f0b00a3;
        public static final int summary_stats_widget_appsno_preference=0x7f0b00a4;
        public static final int summary_weighted_recents_preference=0x7f0b00a5;
        public static final int summary_wildcard_preference=0x7f0b00a6;
        public static final int switched_icon_packs_alert=0x7f0b00a7;
        public static final int title_activity_apps_widget=0x7f0b00a8;
        public static final int title_activity_settings=0x7f0b00a9;
        public static final int title_activity_stats_widget=0x7f0b00aa;
        public static final int title_alignment_preference=0x7f0b00ab;
        public static final int title_appearance=0x7f0b00ac;
        public static final int title_apps=0x7f0b00ad;
        public static final int title_apps_by_widget_size_preference=0x7f0b00ae;
        public static final int title_appsno_preference=0x7f0b00af;
        public static final int title_background_color_preference=0x7f0b00b0;
        public static final int title_behavior=0x7f0b00b1;
        public static final int title_boot_preference=0x7f0b00b2;
        public static final int title_colorize_preference=0x7f0b00b3;
        public static final int title_divider_preference=0x7f0b00b4;
        public static final int title_floating_windows=0x7f0b00b5;
        public static final int title_general=0x7f0b00b6;
        public static final int title_icon_color_category=0x7f0b00b7;
        public static final int title_icon_color_preference=0x7f0b00b8;
        public static final int title_icon_pack_choose_from=0x7f0b00b9;
        public static final int title_icon_pack_install=0x7f0b00ba;
        public static final int title_icon_pack_no_single_picks=0x7f0b00bb;
        public static final int title_icon_pack_no_single_ui=0x7f0b00bc;
        public static final int title_icon_pack_not_found=0x7f0b00bd;
        public static final int title_icon_pack_picker=0x7f0b00be;
        public static final int title_icon_pack_preference=0x7f0b00bf;
        public static final int title_icon_size_preference=0x7f0b00c0;
        public static final int title_ignore_pinned_preference=0x7f0b00c1;
        public static final int title_lollipop_category=0x7f0b00c2;
        public static final int title_more_apps=0x7f0b00c3;
        public static final int title_more_apps_category=0x7f0b00c4;
        public static final int title_more_apps_icon=0x7f0b00c5;
        public static final int title_more_apps_pages=0x7f0b00c6;
        public static final int title_notification_bg_preference=0x7f0b00c7;
        public static final int title_pinned_category=0x7f0b00c8;
        public static final int title_pinned_placement_preference=0x7f0b00c9;
        public static final int title_pinned_sort_preference=0x7f0b00ca;
        public static final int title_priority_preference=0x7f0b00cb;
        public static final int title_rounded_corners_preference=0x7f0b00cc;
        public static final int title_row_divider_preference=0x7f0b00cd;
        public static final int title_second_row_preference=0x7f0b00ce;
        public static final int title_smart_notification=0x7f0b00cf;
        public static final int title_sort_spinner=0x7f0b00d0;
        public static final int title_stats_widget_appsno_ls_preference=0x7f0b00d1;
        public static final int title_stats_widget_appsno_preference=0x7f0b00d2;
        public static final int title_statusbar_icon_preference=0x7f0b00d3;
        public static final int title_toggle_preference=0x7f0b00d4;
        public static final int title_top_spinner=0x7f0b00d5;
        public static final int title_weight_category=0x7f0b00d6;
        public static final int title_weight_priority_preference=0x7f0b00d7;
        public static final int title_weighted_recents_preference=0x7f0b00d8;
        public static final int top_blacklisted=0x7f0b00d9;
        public static final int top_none=0x7f0b00da;
        public static final int top_pinned=0x7f0b00db;
        public static final int us_permission_head=0x7f0b00dc;
        public static final int us_permission_notification=0x7f0b00dd;
        public static final int us_permission_settings_button=0x7f0b00de;
        public static final int us_permission_title=0x7f0b00df;
        public static final int weight_priority_default=0x7f0b00e0;
        public static final int weight_priority_launches=0x7f0b00e1;
        public static final int weight_priority_recency=0x7f0b00e2;
        public static final int weight_priority_time=0x7f0b00e3;
    }
    public static final class style {
        /**  Customize your theme here. 
 Customize your theme here. 
         */
        public static final int AppTheme=0x7f0c0000;
        public static final int TextAppearance_TabPageIndicator=0x7f0c0001;
        public static final int Theme_PageIndicatorDefaults=0x7f0c0002;
        public static final int Widget=0x7f0c0003;
        public static final int Widget_IconPageIndicator=0x7f0c0004;
        public static final int Widget_TabPageIndicator=0x7f0c0005;
    }
    public static final class xml {
        public static final int appswidget=0x7f050000;
        public static final int statswidget=0x7f050001;
    }
    public static final class styleable {
        /** Attributes that can be used with a CirclePageIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CirclePageIndicator_android_background android:background}</code></td><td></td></tr>
           <tr><td><code>{@link #CirclePageIndicator_android_orientation android:orientation}</code></td><td></td></tr>
           <tr><td><code>{@link #CirclePageIndicator_centered ca.mimic.apphangar:centered}</code></td><td></td></tr>
           <tr><td><code>{@link #CirclePageIndicator_fillColor ca.mimic.apphangar:fillColor}</code></td><td></td></tr>
           <tr><td><code>{@link #CirclePageIndicator_pageColor ca.mimic.apphangar:pageColor}</code></td><td></td></tr>
           <tr><td><code>{@link #CirclePageIndicator_radius ca.mimic.apphangar:radius}</code></td><td></td></tr>
           <tr><td><code>{@link #CirclePageIndicator_snap ca.mimic.apphangar:snap}</code></td><td></td></tr>
           <tr><td><code>{@link #CirclePageIndicator_strokeColor ca.mimic.apphangar:strokeColor}</code></td><td></td></tr>
           <tr><td><code>{@link #CirclePageIndicator_strokeWidth ca.mimic.apphangar:strokeWidth}</code></td><td></td></tr>
           </table>
           @see #CirclePageIndicator_android_background
           @see #CirclePageIndicator_android_orientation
           @see #CirclePageIndicator_centered
           @see #CirclePageIndicator_fillColor
           @see #CirclePageIndicator_pageColor
           @see #CirclePageIndicator_radius
           @see #CirclePageIndicator_snap
           @see #CirclePageIndicator_strokeColor
           @see #CirclePageIndicator_strokeWidth
         */
        public static final int[] CirclePageIndicator = {
            0x010100c4, 0x010100d4, 0x7f010000, 0x7f010002,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#background}
          attribute's value can be found in the {@link #CirclePageIndicator} array.
          @attr name android:background
        */
        public static final int CirclePageIndicator_android_background = 1;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#orientation}
          attribute's value can be found in the {@link #CirclePageIndicator} array.
          @attr name android:orientation
        */
        public static final int CirclePageIndicator_android_orientation = 0;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#centered}
          attribute's value can be found in the {@link #CirclePageIndicator} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:centered
        */
        public static final int CirclePageIndicator_centered = 2;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#fillColor}
          attribute's value can be found in the {@link #CirclePageIndicator} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:fillColor
        */
        public static final int CirclePageIndicator_fillColor = 4;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#pageColor}
          attribute's value can be found in the {@link #CirclePageIndicator} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:pageColor
        */
        public static final int CirclePageIndicator_pageColor = 5;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#radius}
          attribute's value can be found in the {@link #CirclePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:radius
        */
        public static final int CirclePageIndicator_radius = 6;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#snap}
          attribute's value can be found in the {@link #CirclePageIndicator} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:snap
        */
        public static final int CirclePageIndicator_snap = 7;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#strokeColor}
          attribute's value can be found in the {@link #CirclePageIndicator} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:strokeColor
        */
        public static final int CirclePageIndicator_strokeColor = 8;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#strokeWidth}
          attribute's value can be found in the {@link #CirclePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:strokeWidth
        */
        public static final int CirclePageIndicator_strokeWidth = 3;
        /** Attributes that can be used with a LinePageIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #LinePageIndicator_android_background android:background}</code></td><td></td></tr>
           <tr><td><code>{@link #LinePageIndicator_centered ca.mimic.apphangar:centered}</code></td><td></td></tr>
           <tr><td><code>{@link #LinePageIndicator_gapWidth ca.mimic.apphangar:gapWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #LinePageIndicator_lineWidth ca.mimic.apphangar:lineWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #LinePageIndicator_selectedColor ca.mimic.apphangar:selectedColor}</code></td><td></td></tr>
           <tr><td><code>{@link #LinePageIndicator_strokeWidth ca.mimic.apphangar:strokeWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #LinePageIndicator_unselectedColor ca.mimic.apphangar:unselectedColor}</code></td><td></td></tr>
           </table>
           @see #LinePageIndicator_android_background
           @see #LinePageIndicator_centered
           @see #LinePageIndicator_gapWidth
           @see #LinePageIndicator_lineWidth
           @see #LinePageIndicator_selectedColor
           @see #LinePageIndicator_strokeWidth
           @see #LinePageIndicator_unselectedColor
         */
        public static final int[] LinePageIndicator = {
            0x010100d4, 0x7f010000, 0x7f010001, 0x7f010002,
            0x7f010003, 0x7f010009, 0x7f01000a
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#background}
          attribute's value can be found in the {@link #LinePageIndicator} array.
          @attr name android:background
        */
        public static final int LinePageIndicator_android_background = 0;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#centered}
          attribute's value can be found in the {@link #LinePageIndicator} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:centered
        */
        public static final int LinePageIndicator_centered = 1;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#gapWidth}
          attribute's value can be found in the {@link #LinePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:gapWidth
        */
        public static final int LinePageIndicator_gapWidth = 6;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#lineWidth}
          attribute's value can be found in the {@link #LinePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:lineWidth
        */
        public static final int LinePageIndicator_lineWidth = 5;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#selectedColor}
          attribute's value can be found in the {@link #LinePageIndicator} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:selectedColor
        */
        public static final int LinePageIndicator_selectedColor = 2;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#strokeWidth}
          attribute's value can be found in the {@link #LinePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:strokeWidth
        */
        public static final int LinePageIndicator_strokeWidth = 3;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#unselectedColor}
          attribute's value can be found in the {@link #LinePageIndicator} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:unselectedColor
        */
        public static final int LinePageIndicator_unselectedColor = 4;
        /** Attributes that can be used with a TitlePageIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #TitlePageIndicator_android_background android:background}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_android_textColor android:textColor}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_android_textSize android:textSize}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_clipPadding ca.mimic.apphangar:clipPadding}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerColor ca.mimic.apphangar:footerColor}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerIndicatorHeight ca.mimic.apphangar:footerIndicatorHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerIndicatorStyle ca.mimic.apphangar:footerIndicatorStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerIndicatorUnderlinePadding ca.mimic.apphangar:footerIndicatorUnderlinePadding}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerLineHeight ca.mimic.apphangar:footerLineHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerPadding ca.mimic.apphangar:footerPadding}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_linePosition ca.mimic.apphangar:linePosition}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_selectedBold ca.mimic.apphangar:selectedBold}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_selectedColor ca.mimic.apphangar:selectedColor}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_titlePadding ca.mimic.apphangar:titlePadding}</code></td><td></td></tr>
           <tr><td><code>{@link #TitlePageIndicator_topPadding ca.mimic.apphangar:topPadding}</code></td><td></td></tr>
           </table>
           @see #TitlePageIndicator_android_background
           @see #TitlePageIndicator_android_textColor
           @see #TitlePageIndicator_android_textSize
           @see #TitlePageIndicator_clipPadding
           @see #TitlePageIndicator_footerColor
           @see #TitlePageIndicator_footerIndicatorHeight
           @see #TitlePageIndicator_footerIndicatorStyle
           @see #TitlePageIndicator_footerIndicatorUnderlinePadding
           @see #TitlePageIndicator_footerLineHeight
           @see #TitlePageIndicator_footerPadding
           @see #TitlePageIndicator_linePosition
           @see #TitlePageIndicator_selectedBold
           @see #TitlePageIndicator_selectedColor
           @see #TitlePageIndicator_titlePadding
           @see #TitlePageIndicator_topPadding
         */
        public static final int[] TitlePageIndicator = {
            0x01010095, 0x01010098, 0x010100d4, 0x7f010001,
            0x7f01000b, 0x7f01000c, 0x7f01000d, 0x7f01000e,
            0x7f01000f, 0x7f010010, 0x7f010011, 0x7f010012,
            0x7f010013, 0x7f010014, 0x7f010015
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#background}
          attribute's value can be found in the {@link #TitlePageIndicator} array.
          @attr name android:background
        */
        public static final int TitlePageIndicator_android_background = 2;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#textColor}
          attribute's value can be found in the {@link #TitlePageIndicator} array.
          @attr name android:textColor
        */
        public static final int TitlePageIndicator_android_textColor = 1;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#textSize}
          attribute's value can be found in the {@link #TitlePageIndicator} array.
          @attr name android:textSize
        */
        public static final int TitlePageIndicator_android_textSize = 0;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#clipPadding}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:clipPadding
        */
        public static final int TitlePageIndicator_clipPadding = 4;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#footerColor}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:footerColor
        */
        public static final int TitlePageIndicator_footerColor = 5;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#footerIndicatorHeight}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:footerIndicatorHeight
        */
        public static final int TitlePageIndicator_footerIndicatorHeight = 8;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#footerIndicatorStyle}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>triangle</code></td><td>1</td><td></td></tr>
<tr><td><code>underline</code></td><td>2</td><td></td></tr>
</table>
          @attr name ca.mimic.apphangar:footerIndicatorStyle
        */
        public static final int TitlePageIndicator_footerIndicatorStyle = 7;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#footerIndicatorUnderlinePadding}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:footerIndicatorUnderlinePadding
        */
        public static final int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#footerLineHeight}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:footerLineHeight
        */
        public static final int TitlePageIndicator_footerLineHeight = 6;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#footerPadding}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:footerPadding
        */
        public static final int TitlePageIndicator_footerPadding = 10;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#linePosition}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>bottom</code></td><td>0</td><td></td></tr>
<tr><td><code>top</code></td><td>1</td><td></td></tr>
</table>
          @attr name ca.mimic.apphangar:linePosition
        */
        public static final int TitlePageIndicator_linePosition = 11;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#selectedBold}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:selectedBold
        */
        public static final int TitlePageIndicator_selectedBold = 12;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#selectedColor}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:selectedColor
        */
        public static final int TitlePageIndicator_selectedColor = 3;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#titlePadding}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:titlePadding
        */
        public static final int TitlePageIndicator_titlePadding = 13;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#topPadding}
          attribute's value can be found in the {@link #TitlePageIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:topPadding
        */
        public static final int TitlePageIndicator_topPadding = 14;
        /** Attributes that can be used with a UnderlinePageIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #UnderlinePageIndicator_android_background android:background}</code></td><td></td></tr>
           <tr><td><code>{@link #UnderlinePageIndicator_fadeDelay ca.mimic.apphangar:fadeDelay}</code></td><td></td></tr>
           <tr><td><code>{@link #UnderlinePageIndicator_fadeLength ca.mimic.apphangar:fadeLength}</code></td><td></td></tr>
           <tr><td><code>{@link #UnderlinePageIndicator_fades ca.mimic.apphangar:fades}</code></td><td></td></tr>
           <tr><td><code>{@link #UnderlinePageIndicator_selectedColor ca.mimic.apphangar:selectedColor}</code></td><td></td></tr>
           </table>
           @see #UnderlinePageIndicator_android_background
           @see #UnderlinePageIndicator_fadeDelay
           @see #UnderlinePageIndicator_fadeLength
           @see #UnderlinePageIndicator_fades
           @see #UnderlinePageIndicator_selectedColor
         */
        public static final int[] UnderlinePageIndicator = {
            0x010100d4, 0x7f010001, 0x7f010016, 0x7f010017,
            0x7f010018
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#background}
          attribute's value can be found in the {@link #UnderlinePageIndicator} array.
          @attr name android:background
        */
        public static final int UnderlinePageIndicator_android_background = 0;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#fadeDelay}
          attribute's value can be found in the {@link #UnderlinePageIndicator} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:fadeDelay
        */
        public static final int UnderlinePageIndicator_fadeDelay = 3;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#fadeLength}
          attribute's value can be found in the {@link #UnderlinePageIndicator} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:fadeLength
        */
        public static final int UnderlinePageIndicator_fadeLength = 4;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#fades}
          attribute's value can be found in the {@link #UnderlinePageIndicator} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:fades
        */
        public static final int UnderlinePageIndicator_fades = 2;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#selectedColor}
          attribute's value can be found in the {@link #UnderlinePageIndicator} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name ca.mimic.apphangar:selectedColor
        */
        public static final int UnderlinePageIndicator_selectedColor = 1;
        /** Attributes that can be used with a ViewPagerIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiCirclePageIndicatorStyle ca.mimic.apphangar:vpiCirclePageIndicatorStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiIconPageIndicatorStyle ca.mimic.apphangar:vpiIconPageIndicatorStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiLinePageIndicatorStyle ca.mimic.apphangar:vpiLinePageIndicatorStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiTabPageIndicatorStyle ca.mimic.apphangar:vpiTabPageIndicatorStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiTitlePageIndicatorStyle ca.mimic.apphangar:vpiTitlePageIndicatorStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiUnderlinePageIndicatorStyle ca.mimic.apphangar:vpiUnderlinePageIndicatorStyle}</code></td><td></td></tr>
           </table>
           @see #ViewPagerIndicator_vpiCirclePageIndicatorStyle
           @see #ViewPagerIndicator_vpiIconPageIndicatorStyle
           @see #ViewPagerIndicator_vpiLinePageIndicatorStyle
           @see #ViewPagerIndicator_vpiTabPageIndicatorStyle
           @see #ViewPagerIndicator_vpiTitlePageIndicatorStyle
           @see #ViewPagerIndicator_vpiUnderlinePageIndicatorStyle
         */
        public static final int[] ViewPagerIndicator = {
            0x7f010019, 0x7f01001a, 0x7f01001b, 0x7f01001c,
            0x7f01001d, 0x7f01001e
        };
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#vpiCirclePageIndicatorStyle}
          attribute's value can be found in the {@link #ViewPagerIndicator} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name ca.mimic.apphangar:vpiCirclePageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#vpiIconPageIndicatorStyle}
          attribute's value can be found in the {@link #ViewPagerIndicator} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name ca.mimic.apphangar:vpiIconPageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#vpiLinePageIndicatorStyle}
          attribute's value can be found in the {@link #ViewPagerIndicator} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name ca.mimic.apphangar:vpiLinePageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#vpiTabPageIndicatorStyle}
          attribute's value can be found in the {@link #ViewPagerIndicator} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name ca.mimic.apphangar:vpiTabPageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#vpiTitlePageIndicatorStyle}
          attribute's value can be found in the {@link #ViewPagerIndicator} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name ca.mimic.apphangar:vpiTitlePageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
        /**
          <p>This symbol is the offset where the {@link ca.mimic.apphangar.R.attr#vpiUnderlinePageIndicatorStyle}
          attribute's value can be found in the {@link #ViewPagerIndicator} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name ca.mimic.apphangar:vpiUnderlinePageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
    };
}
