/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.kw.shrdlu.grtgtfs;

public final class R {
    public static final class anim {
        public static final int slide_in=0x7f040000;
        public static final int slide_out=0x7f040001;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int grt_blue=0x7f060000;
        public static final int grt_yellow=0x7f060001;
        public static final int list_background=0x7f060002;
        public static final int list_dark_background=0x7f060003;
    }
    public static final class drawable {
        public static final int blank=0x7f020000;
        public static final int bluepin=0x7f020001;
        public static final int grticon=0x7f020002;
        public static final int grticon_home=0x7f020003;
        public static final int grticon_nohome=0x7f020004;
        public static final int ic_menu_add=0x7f020005;
        public static final int ic_menu_compass=0x7f020006;
        public static final int ic_menu_info_details=0x7f020007;
        public static final int ic_menu_moreoverflow_normal_holo_dark=0x7f020008;
        public static final int ic_menu_mylocation=0x7f020009;
        public static final int ic_menu_notifications=0x7f02000a;
        public static final int ic_menu_preferences=0x7f02000b;
        public static final int ic_menu_refresh=0x7f02000c;
        public static final int ic_menu_search=0x7f02000d;
        public static final int progress_horizontal=0x7f02000e;
        public static final int routenumber=0x7f02000f;
        public static final int stopnumber=0x7f020010;
    }
    public static final class id {
        public static final int about_credits=0x7f0a0001;
        public static final int about_header=0x7f0a0000;
        public static final int button_overflow=0x7f0a0011;
        public static final int button_search=0x7f0a0012;
        public static final int button_searchroutes=0x7f0a000d;
        public static final int button_searchstops=0x7f0a000c;
        public static final int desc=0x7f0a000a;
        public static final int detail_area=0x7f0a000e;
        public static final int label=0x7f0a0008;
        public static final int listtitle=0x7f0a0013;
        public static final int mapview=0x7f0a0007;
        public static final int menu_about=0x7f0a001b;
        public static final int menu_alerts=0x7f0a0018;
        public static final int menu_closeststops=0x7f0a0017;
        public static final int menu_preferences=0x7f0a001a;
        public static final int menu_refresh=0x7f0a0016;
        public static final int menu_search=0x7f0a0015;
        public static final int menu_showmap=0x7f0a0019;
        public static final int progress=0x7f0a0014;
        public static final int routedesc=0x7f0a0006;
        public static final int routelabel=0x7f0a0005;
        public static final int searchtext=0x7f0a000b;
        public static final int stopdesc=0x7f0a0003;
        public static final int stoplabel=0x7f0a0002;
        public static final int stoptime=0x7f0a0004;
        public static final int title=0x7f0a0010;
        public static final int titlelogo=0x7f0a000f;
        public static final int value=0x7f0a0009;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int favouritesrow=0x7f030001;
        public static final int mapview=0x7f030002;
        public static final int mapview_debug=0x7f030003;
        public static final int route_numanddesc=0x7f030004;
        public static final int row2layout=0x7f030005;
        public static final int rowlayout=0x7f030006;
        public static final int searchlayout=0x7f030007;
        public static final int stop_numanddesc=0x7f030008;
        public static final int timeslayout=0x7f030009;
        public static final int timestopdesc=0x7f03000a;
        public static final int titlelayout=0x7f03000b;
        public static final int tweetlayout=0x7f03000c;
    }
    public static final class menu {
        public static final int busstopsmenu=0x7f090000;
    }
    public static final class string {
        public static final int about=0x7f070000;
        public static final int ampmtimes=0x7f070001;
        public static final int app_credits=0x7f070003;
        public static final int app_description=0x7f070002;
        public static final int app_name=0x7f070004;
        public static final int app_short_name=0x7f070005;
        public static final int auto_check4dbupdate=0x7f070006;
        public static final int button_routes=0x7f070007;
        public static final int button_stops=0x7f070008;
        public static final int calendar_expired=0x7f070009;
        public static final int cancel=0x7f07000a;
        public static final int closest_stops=0x7f07000b;
        public static final int cntinue=0x7f07000c;
        public static final int corrupt_exit=0x7f07000d;
        public static final int db_download_now=0x7f07000f;
        public static final int db_downloading=0x7f070010;
        public static final int db_is_awol=0x7f07000e;
        public static final int db_is_corrupt=0x7f070011;
        public static final int db_new_avail=0x7f070012;
        public static final int db_not_avail=0x7f070013;
        public static final int db_opening=0x7f070014;
        public static final int exit=0x7f070015;
        public static final int favs_add_to_list=0x7f070016;
        public static final int favs_remove_from_list=0x7f070017;
        public static final int favs_reorder_item=0x7f070018;
        public static final int find_route=0x7f070019;
        public static final int find_stop=0x7f07001a;
        public static final int ga_api_key=0x7f07001b;
        public static final int last_location_fix=0x7f07001c;
        public static final int legal_notices=0x7f07001d;
        public static final int loading_routes=0x7f07001e;
        public static final int loading_stops=0x7f07001f;
        public static final int loading_times=0x7f070020;
        public static final int longpress_adds_stop=0x7f070021;
        public static final int longpress_removes_stop=0x7f070022;
        public static final int menu_settings=0x7f070023;
        public static final int mylocation=0x7f070024;
        public static final int no=0x7f070025;
        public static final int no_favourites=0x7f070026;
        public static final int no_location_fix=0x7f070027;
        public static final int no_more_busses=0x7f070028;
        public static final int pref_ampmtimes_key=0x7f07002a;
        public static final int pref_db_autoupdate_key=0x7f07002b;
        public static final int pref_favstops_key=0x7f07002c;
        public static final int pref_showallbusses_key=0x7f07002d;
        public static final int pref_uuid_key=0x7f07002e;
        public static final int preferences=0x7f070029;
        public static final int refresh=0x7f07002f;
        public static final int rider_alerts=0x7f070030;
        public static final int route_fling=0x7f070031;
        public static final int search_hint=0x7f070032;
        public static final int showallbusses=0x7f070033;
        public static final int showmap=0x7f070034;
        public static final int stop_unused=0x7f070035;
        public static final int tap_time_for_route=0x7f070036;
        public static final int tap_time_for_trip=0x7f070037;
        public static final int title_activity_closest_stops=0x7f070038;
        public static final int title_favourites=0x7f070039;
        public static final int title_mapstops=0x7f07003a;
        public static final int title_rider_alerts=0x7f07003b;
        public static final int title_search=0x7f07003c;
        public static final int twitter_fetch_failed=0x7f07003d;
        public static final int twitter_fetch_nothing=0x7f07003e;
        public static final int twitter_querying_feed=0x7f07003f;
        public static final int yes=0x7f070040;
    }
    public static final class style {
        /**  Let the system draw the title bar, with an ActionBar 
         */
        public static final int ActivityTheme=0x7f080001;
        public static final int List=0x7f080005;
        public static final int List_Body=0x7f080008;
        public static final int List_Content=0x7f080009;
        public static final int List_Label=0x7f080007;
        public static final int List_Rightlabel=0x7f08000c;
        public static final int List_RouteandStoplabel=0x7f08000f;
        public static final int List_Routelabel=0x7f080011;
        public static final int List_Stopbusname=0x7f08000e;
        public static final int List_Stoplabel=0x7f080010;
        public static final int List_Stoptime=0x7f08000d;
        public static final int List_Title=0x7f080006;
        public static final int List_TweetText=0x7f08000b;
        public static final int List_TweetTime=0x7f08000a;
        public static final int Text=0x7f080002;
        public static final int Text_Loading=0x7f080003;
        public static final int Text_Title=0x7f080004;
        public static final int appGlobalTheme=0x7f080012;
        public static final int progressbar=0x7f080000;
    }
    public static final class xml {
        public static final int preferences=0x7f050000;
    }
}
